apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roi-dtc-m2022-u318/internal-image:v2.0.0
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "roi-dtc-m2022-u318"
        ports:
        - containerPort: 8082
            
        
